# Generated by Django 3.2 on 2022-07-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
