# Generated by Django 3.2 on 2022-08-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algos', '0003_algo_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algo',
            name='image_url',
        ),
    ]
