# Generated by Django 3.2 on 2022-08-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algos', '0004_remove_algo_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='algos.algo')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
