# Generated by Django 3.2 on 2022-08-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algos', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
