# Generated by Django 3.2 on 2022-08-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algos', '0006_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='algo',
            name='keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='algo',
            name='total_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='algo',
            name='volatility',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
