# Generated by Django 3.2 on 2022-08-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algos', '0007_auto_20220807_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algo',
            name='total_return',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='algo',
            name='volatility',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
