# Generated by Django 3.2 on 2022-08-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ['term'], 'verbose_name_plural': 'Terms'},
        ),
    ]
