# Generated by Django 3.2 on 2022-08-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_terms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
